### ISSUE TITLE
'module' object has no attribute 'Todos'

### ISSUE THREAD

**Issue by xiang578** [bevesce/SublimeTodoflow#3]
hello
when i run this packege command in sublime, i meet a problem.

In sublime Console, the error info blew
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/Users/didi/Library/Application Support/Sublime Text 3/Packages/SublimeTodoflow/filter_commands.py", line 13, in run
    self.prepare()
  File "/Users/didi/Library/Application Support/Sublime Text 3/Packages/SublimeTodoflow/filter_commands.py", line 19, in prepare
    self.todos = todoflow.Todos(self.content)
AttributeError: 'module' object has no attribute 'Todos'
```

how can i fix this bug?

in the file filter_commands.py head info was blew:
```python
from .todoflow import todoflow
from .todoflow.todoflow import textutils
from . import datedrop
import sublime
import sublime_plugin
import re
```
what the mean of "from .todoflow import todoflow"

**Comment by bevesce** [comment]
Do you have `todoflow` directory in your `Sublime Text 3/Packages/SublimeTodoflow/` directory?

**Comment by xiang578** [comment]
yes, I slove this problom by reinstall sublime
